command /ume-barrel-reload:
	permission: mtt.admin
	trigger:
    
    	#barrel-lvl1
		set {ume-b-1-1} to a random integer from 1 to 10
		set {ume-b-1-1-op} to a random integer from 1 to 2
		set {ume-b-1-2} to a random integer from 1 to 10
		set {ume-b-1-2-op} to a random integer from 1 to 2
		set {ume-b-1-3} to a random integer from 1 to 10
		set {ume-b-1-3-op} to a random integer from 1 to 2

		#barrel-lvl2
		set {ume-b-2-1} to a random integer from 1 to 10
		set {ume-b-2-2} to a random integer from 1 to 10
		set {ume-b-2-3} to a random integer from 1 to 10

#Barrel Loot Stuff 60% - Common Chest, 30% Gold Chest, 10% God Chest

#PART1

        #barrel 1-1
        
        #common
		if {ume-b-1-1} is 1:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 4 4 47"
			
		if {ume-b-1-1} is 2:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 4 4 47"
			
		if {ume-b-1-1} is 3:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 4 4 47"
			
		if {ume-b-1-1} is 4:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 4 4 47"
	
		if {ume-b-1-1} is 5:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 4 4 47"
			
		if {ume-b-1-1} is 6:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 4 4 47"
			
		#gold
		if {ume-b-1-1} is 7:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 4 4 47"
	
		if {ume-b-1-1} is 8:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 4 4 47"
			
		if {ume-b-1-1} is 9:
			execute console command "/sudo playerName clone -33 15 40 -33 15 40 4 4 47"
		#god
		if {ume-b-1-1} is 10:
			if {ume-b-1-1-op} is 1:
				execute console command "/sudo playerName -39 15 44 -39 15 44 4 4 47"
			else if {ume-b-1-1-op} is 2:
				execute console command "/sudo playerName -39 15 40 -39 15 40 4 4 47"
			else:
				execute console command "/sudo playerName clone -33 15 40 -33 15 40 4 4 47"

        
        #barrel 1-2

        #common
		if {ume-b-1-2} is 1:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 141 8 29"
			
		if {ume-b-1-2} is 2:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 141 8 29"
			
		if {ume-b-1-2} is 3:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 141 8 29"
			
		if {ume-b-1-2} is 4:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 141 8 29"
	
		if {ume-b-1-2} is 5:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 141 8 29"
			
		if {ume-b-1-2} is 6:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 141 8 29"
			
		#gold
		if {ume-b-1-2} is 7:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 141 8 29"
	
		if {ume-b-1-2} is 8:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 141 8 29"
			
		if {ume-b-1-2} is 9:
			execute console command "/sudo playerName clone -33 15 40 -33 15 40 141 8 29"
		#god
		if {ume-b-1-2} is 10:
			if {ume-b-1-2-op} is 1:
				execute console command "/sudo playerName -39 15 44 -39 15 44 141 8 29"
			else if {ume-b-1-2-op} is 2:
				execute console command "/sudo playerName -39 15 40 -39 15 40 141 8 29"
			else:
				execute console command "/sudo playerName clone -33 15 40 -33 15 40 141 8 29"

        #barrel 1-3
        
        #common
		if {ume-b-1-3} is 1:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 65 5 -31"
			
		if {ume-b-1-3} is 2:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 65 5 -31"
			
		if {ume-b-1-3} is 3:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 65 5 -31"
			
		if {ume-b-1-3} is 4:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 65 5 -31"
	
		if {ume-b-1-3} is 5:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 65 5 -31"
			
		if {ume-b-1-3} is 6:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 65 5 -31"
			
		#gold
		if {ume-b-1-3} is 7:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 65 5 -31"
	
		if {ume-b-1-3} is 8:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 65 5 -31"
			
		if {ume-b-1-3} is 9:
			execute console command "/sudo playerName clone -33 15 40 -33 15 40 65 5 -31"
		#god
		if {ume-b-1-3} is 10:
			if {ume-b-1-3-op} is 1:
				execute console command "/sudo playerName -39 15 44 -39 15 44 65 5 -31"
			else if {ume-b-1-3-op} is 2:
				execute console command "/sudo playerName -39 15 40 -39 15 40 65 5 -31"
			else:
				execute console command "/sudo playerName clone -33 15 40 -33 15 40 65 5 -31"

			
#PART2

        #barrel 2-1
        
        #common
		if {ume-b-2-1} is 1:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 113 5 43"
			
		if {ume-b-2-1} is 2:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 113 5 43"
			
		if {ume-b-2-1} is 3:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 113 5 43"
			
		if {ume-b-2-1} is 4:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 113 5 43"
	
		if {ume-b-2-1} is 5:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 113 5 43"
			
		if {ume-b-2-1} is 6:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 113 5 43"
			
		#gold
		if {ume-b-2-1} is 7:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 113 5 43"
	
		if {ume-b-2-1} is 8:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 113 5 43"
			
		if {ume-b-2-1} is 9:
			execute console command "/sudo playerName clone -33 15 40 -33 15 40 113 5 43"
		#god
		if {ume-b-2-1} is 10:
			if {ume-b-2-1-op} is 1:
				execute console command "/sudo playerName -39 15 44 -39 15 44 113 5 43"
			else if {ume-b-2-1-op} is 2:
				execute console command "/sudo playerName -39 15 40 -39 15 40 113 5 43"
			else:
				execute console command "/sudo playerName clone -33 15 40 -33 15 40 113 5 43"
        
        #barrel 2-2

        #common
		if {ume-b-2-2} is 1:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 114 4 43"
			
		if {ume-b-2-2} is 2:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 114 4 43"
			
		if {ume-b-2-2} is 3:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 114 4 43"
			
		if {ume-b-2-2} is 4:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 114 4 43"
	
		if {ume-b-2-2} is 5:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 114 4 43"
			
		if {ume-b-2-2} is 6:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 114 4 43"
			
		#gold
		if {ume-b-2-2} is 7:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 114 4 43"
	
		if {ume-b-2-2} is 8:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 114 4 43"
			
		if {ume-b-2-2} is 9:
			execute console command "/sudo playerName clone -33 15 40 -33 15 40 114 4 43"
		#god
		if {ume-b-2-2} is 10:
			if {ume-b-2-2-op} is 1:
				execute console command "/sudo playerName -39 15 44 -39 15 44 114 4 43"
			else if {ume-b-2-2-op} is 2:
				execute console command "/sudo playerName -39 15 40 -39 15 40 114 4 43"
			else:
				execute console command "/sudo playerName clone -33 15 40 -33 15 40 114 4 43"

        #barrel 2-3

        #common
		if {ume-b-2-3} is 1:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 113 4 42"
			
		if {ume-b-2-3} is 2:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 113 4 42"
			
		if {ume-b-2-3} is 3:
			execute console command "/sudo playerName clone -27 15 44 -27 15 44 113 4 42"
			
		if {ume-b-2-3} is 4:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 113 4 42"
	
		if {ume-b-2-3} is 5:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 113 4 42"
			
		if {ume-b-2-3} is 6:
			execute console command "/sudo playerName clone -27 15 40 -27 15 40 113 4 42"
			
		#gold
		if {ume-b-2-3} is 7:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 113 4 42"
	
		if {ume-b-2-3} is 8:
			execute console command "/sudo playerName clone -33 15 44 -33 15 44 113 4 42"
			
		if {ume-b-2-3} is 9:
			execute console command "/sudo playerName clone -33 15 40 -33 15 40 113 4 42"
		#god
		if {ume-b-2-3} is 10:
			if {ume-b-2-3-op} is 1:
				execute console command "/sudo playerName -39 15 44 -39 15 44 113 4 42"
			else if {ume-b-2-3-op} is 2:
				execute console command "/sudo playerName -39 15 40 -39 15 40 113 4 42"
			else:
				execute console command "/sudo playerName clone -33 15 40 -33 15 40 113 4 42"